### ISSUE TITLE
TypeError: Cannot convert a Symbol value to a string (jQuery)

### ISSUE THREAD

**Issue by TusharRakheja** [joescii/sbt-js-test#12]
I added [jQuery](https://code.jquery.com/jquery-3.2.1.min.js) as a jsResource (prettified [here](https://gist.github.com/TusharRakheja/04971b2673279dd3051e622167b844ef) for line numbers). On running jsTest, I get this error:

```
[error] runtimeError: message=[TypeError: Cannot convert a Symbol value to a string] sourceName=[file:/C:/Users/T22KOX3/Desktop/test/testproject/public/javascripts/libs/jquery.min.js] line=[38] lineSource=[null] lineOffset=[0]
com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot convert a Symbol value to a string (file:/C:/Users/T22KOX3/Desktop/test/testproject/public/javascripts/libs/jquery.min.js#38)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:954)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:628)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:513)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:836)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:812)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:997)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:399)
	at com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:277)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:293)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:799)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:756)
	at org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
	at org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
	at org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
	at org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:330)
	at org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3126)
	at org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2093)
	at org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:920)
	at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
	at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:1039)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:252)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:198)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:271)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:159)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:478)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:352)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:417)
	at com.joescii.sbtjs.SbtJsTestTasks$.com$joescii$sbtjs$SbtJsTestTasks$$runJs(SbtJsTestTasks.scala:101)
	at com.joescii.sbtjs.SbtJsTestTasks$$anonfun$com$joescii$sbtjs$SbtJsTestTasks$$runTests$1.apply(SbtJsTestTasks.scala:151)
	at com.joescii.sbtjs.SbtJsTestTasks$$anonfun$com$joescii$sbtjs$SbtJsTestTasks$$runTests$1.apply(SbtJsTestTasks.scala:149)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at com.joescii.sbtjs.SbtJsTestTasks$.com$joescii$sbtjs$SbtJsTestTasks$$runTests(SbtJsTestTasks.scala:149)
	at com.joescii.sbtjs.SbtJsTestTasks$$anonfun$4.apply(SbtJsTestTasks.scala:159)
	at com.joescii.sbtjs.SbtJsTestTasks$$anonfun$4.apply(SbtJsTestTasks.scala:156)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: net.sourceforge.htmlunit.corejs.javascript.EvaluatorException: TypeError: Cannot convert a Symbol value to a string (file:/C:/Users/T22KOX3/Desktop/test/testproject/public/javascripts/libs/jquery.min.js#38)
	at com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter.runtimeError(StrictErrorReporter.java:83)
	at net.sourceforge.htmlunit.corejs.javascript.Context.reportRuntimeError(Context.java:1090)
	at net.sourceforge.htmlunit.corejs.javascript.Context.reportRuntimeError(Context.java:1137)
	at com.gargoylesoftware.htmlunit.javascript.host.Symbol.getDefaultValue(Symbol.java:117)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.toString(ScriptRuntime.java:855)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.toStringIdOrIndex(ScriptRuntime.java:1439)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.setObjectElem(ScriptRuntime.java:1635)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.setObjectElem(ScriptRuntime.java:1627)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.doSetElem(Interpreter.java:2328)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1275)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:798)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:105)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:411)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:309)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3286)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:115)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:827)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:939)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:628)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:513)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:836)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:812)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:997)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:399)
	at com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:277)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:293)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:799)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:756)
	at org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
	at org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
	at org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
	at org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:330)
	at org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3126)
	at org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2093)
	at org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:920)
	at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
	at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:1039)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:252)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:198)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:271)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:159)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:478)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:352)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:417)
	at com.joescii.sbtjs.SbtJsTestTasks$.com$joescii$sbtjs$SbtJsTestTasks$$runJs(SbtJsTestTasks.scala:101)
	at com.joescii.sbtjs.SbtJsTestTasks$$anonfun$com$joescii$sbtjs$SbtJsTestTasks$$runTests$1.apply(SbtJsTestTasks.scala:151)
	at com.joescii.sbtjs.SbtJsTestTasks$$anonfun$com$joescii$sbtjs$SbtJsTestTasks$$runTests$1.apply(SbtJsTestTasks.scala:149)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at com.joescii.sbtjs.SbtJsTestTasks$.com$joescii$sbtjs$SbtJsTestTasks$$runTests(SbtJsTestTasks.scala:149)
	at com.joescii.sbtjs.SbtJsTestTasks$$anonfun$4.apply(SbtJsTestTasks.scala:159)
	at com.joescii.sbtjs.SbtJsTestTasks$$anonfun$4.apply(SbtJsTestTasks.scala:156)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:jsTest) com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot convert a Symbol value to a string (file:/C:/Users/T22KOX3/Desktop/test/testproject/public/javascripts/libs/jquery.min.js#38)
[error] Total time: 2 s, completed Jul 25, 2017 5:22:29 PM

```

Any idea how to fix this? jQuery itself is working fine in the project. I understand this could be an HtmlUnit issue, but maybe there is a flag that can fix it? Looks like an ES version issue.

**Comment by joescii** [comment]
Looks like `Cannot convert a Symbol value to a string` a pretty common JS problem from a quick google I just did. Can you try a later version of jquery?

**Comment by TusharRakheja** [comment]
I've been using the latest version (3.2.1, minified). I can try the uncompressed, though I don't know if it will be much help.

**Comment by TusharRakheja** [comment]
Yep, that didn't work either. Hmm.
