### ISSUE TITLE
Read JS assets from project webjars

### ISSUE THREAD

**Issue by joescii** [joescii/sbt-js-test#2]

**Comment by retn01** [comment]
Hi, am getting a WebJar error, I think similar to the title of this issue. Was this issue resolved? 

Below is my error:
java.lang.IllegalArgumentException: jasmine.js could not be found. Make sure you've added the corresponding WebJar and please check for typos

**Comment by joescii** [comment]
This issue is for allowing JS libraries other than _jasmine.js_ to be read from the classpath. For instance, you could have a webjar for angular and resolving this issue would make it possible for the JS assets from the angular jar to be read during tests.

Make sure you have added a jasmine web jar to the classpath of the project per the [Installation section of the readme](https://github.com/joescii/sbt-js-test#installation).

**Comment by retn01** [comment]
Yes, I have added the dependencies as mentioned in the readme. jsLs command also works fine and lists the available src js and test js to be tested. 

jsTest leads to above mentioned error

**Comment by joescii** [comment]
Can you share your plugin sbt file?

Joe

**Comment by retn01** [comment]
// The Play plugin

resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.3")

// web plugins

addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.3.5")

resolvers += "Springer Repository" at "http://repo.tools.springer-sbm.com:8081/nexus/content/repositories/releases/"

addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.6.1")

addSbtPlugin("com.typesafe.sbt" % "sbt-traceur" % "1.0.1")

addSbtPlugin("com.typesafe.sbt" % "sbt-web" % "1.4.0")

addSbtPlugin("com.joescii" % "sbt-js-test" % "0.1.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-jshint" % "1.0.3")

addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.1.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-gzip" % "1.0.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.1.0")

**Comment by retn01** [comment]
[info] Writing jasmine2 assets...
java.lang.IllegalArgumentException: jasmine.js could not be found. Make sure you've added the corresponding WebJar and please check for typos.
        at org.webjars.WebJarAssetLocator.throwNotFoundException(WebJarAssetLocator.java:174)
        at org.webjars.WebJarAssetLocator.getFullPath(WebJarAssetLocator.java:231)
        at org.webjars.WebJarAssetLocator.getFullPath(WebJarAssetLocator.java:189)
        at com.joescii.sbtjs.SbtJsTestTasks$.writeJasmineAssets(SbtJsTestTasks.scala:69)
        at com.joescii.sbtjs.SbtJsTestTasks$.com$joescii$sbtjs$SbtJsTestTasks$$runTests(SbtJsTestTasks.scala:135)
        at com.joescii.sbtjs.SbtJsTestTasks$$anonfun$3.apply(SbtJsTestTasks.scala:150)
        at com.joescii.sbtjs.SbtJsTestTasks$$anonfun$3.apply(SbtJsTestTasks.scala:147)

**Comment by joescii** [comment]
Add this line to your plugins sbt file just before the `sbt-js-test` plugin:

``` scala
libraryDependencies += "org.webjars.bower" % "jasmine" % "2.4.1" % "runtime"
```

**Comment by retn01** [comment]
Weird! I had added the dependency in the build.sbt file. Didnt work from there. Now adding it directly to the plugins file helped. Thanks a ton!

**Comment by joescii** [comment]
No problem! It's because sbt itself has a different classpath than your project. An sbt plugin will use the sbt classpath and dependencies, not the project classpath and dependencies. Enjoy!

Joe

**Comment by retn01** [comment]
On another note, does the plugin have an out of the box support for ES6? Trying to use sbt plugins for transpilers. Nothing seems to work for tests right now. Node is the go to way it seems but sbt would have been an ideal solution.

**Comment by joescii** [comment]
The plugin is just a wrapper over [HtmlUnit](http://htmlunit.sourceforge.net/). We support whatever it supports.
